if (!window.PRESET_ICONS) {
  window.PRESET_ICONS = [
    { path: 'img/png/Edge.svg', name: 'Edge' },
    { path: 'img/png/Firefox.svg', name: 'Firefox' },
    { path: 'img/png/Adminer.svg', name: 'Adminer' },
    { path: 'img/png/Ai.svg', name: 'Ai' },
    { path: 'img/png/Alist.svg', name: 'Alist' },
    { path: 'img/png/Aria2.svg', name: 'Aria2' },
    { path: 'img/png/Book.svg', name: 'Book' },
    { path: 'img/png/Calibre.png', name: 'Calibre' },
    { path: 'img/png/Chatgpt.png', name: 'ChatGPT' },
    { path: 'img/png/Cloud.svg', name: 'Cloud' },
    { path: 'img/png/Downloads.png', name: 'Downloads' },
    { path: 'img/png/Emby.svg', name: 'Emby' },
    { path: 'img/png/FaceTime.png', name: 'FaceTime' },
    { path: 'img/png/File.svg', name: 'File' },
    { path: 'img/png/FileBrowser.svg', name: 'FileBrowser' },
    { path: 'img/png/FileSync.svg', name: 'FileSync' },
    { path: 'img/png/HPE.svg', name: 'HPE' },
    { path: 'img/png/Homarr.png', name: 'Homarr' },
    { path: 'img/png/Jellyfin.svg', name: 'Jellyfin' },
    { path: 'img/png/KMS.svg', name: 'KMS' },
    { path: 'img/png/Lucky.svg', name: 'Lucky' },
    { path: 'img/png/MariaDB.svg', name: 'MariaDB' },
    { path: 'img/png/MovieTool.svg', name: 'MovieTool' },
    { path: 'img/png/Music.svg', name: 'Music' },
    { path: 'img/png/MyAdmin.svg', name: 'MyAdmin' },
    { path: 'img/png/NasTool.svg', name: 'NasTool' },
    { path: 'img/png/Openwrt.svg', name: 'OpenWrt' },
    { path: 'img/png/PVE.svg', name: 'PVE' },
    { path: 'img/png/Photos.svg', name: 'Photos' },
    { path: 'img/png/Podcats.png', name: 'Podcasts' },
    { path: 'img/png/Portainer.svg', name: 'Portainer' },
    { path: 'img/png/Print.svg', name: 'Print' },
    { path: 'img/png/Qb.svg', name: 'Qbittorrent' },
    { path: 'img/png/QingLong.svg', name: 'QingLong' },
    { path: 'img/png/S-PDF.svg', name: 'S-PDF' },
    { path: 'img/png/Sam.svg', name: 'Sam' },
    { path: 'img/png/Server.svg', name: 'Server' },
    { path: 'img/png/Settings.png', name: 'Settings' },
    { path: 'img/png/Thunder.png', name: 'Thunder' },
    { path: 'img/png/Transmission.png', name: 'Transmission' },
    { path: 'img/png/Unraid.svg', name: 'Unraid' },
    { path: 'img/png/VM.svg', name: 'VM' },
    { path: 'img/png/Videos.svg', name: 'Videos' },
    { path: 'img/png/XunLei.svg', name: 'XunLei' },
    { path: 'img/png/iCloud-Drive.png', name: 'iCloud Drive' },
    { path: 'img/png/nginxWebUI.png', name: 'nginxWebUI' },
    { path: 'img/png/favicon.svg', name: 'Favicon' },
    { path: 'img/png/favicon2.svg', name: 'Favicon2' },
    { path: 'img/png/logo.svg', name: 'Logo' },
    { path: 'img/png/猫logo2.svg', name: '猫Logo' },
    { path: 'img/png/DPanel.svg', name: 'DPanel' },
    { path: 'img/png/AdGuard.svg', name: 'AdGuard' },
    { path: 'img/png/Esxi.svg', name: 'Esxi' }
  ];
}
